- name: Create directory
  file:
    path: "/etc/prometheus/"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Copy configuration file into a config dir
  template:
    src: "templates/prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    owner: root
    group: root
    mode: '644'

- name: Deploy container
  docker_container:
    name: "prometheus"
    image: "prom/prometheus:main"
    restart_policy: always
    log_driver: "json-file"
    log_options:
      max-size: 1G
    ports:
      - "9090:9090"
    volumes:
      - "/etc/prometheus:/etc/prometheus"
